development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: quiz_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: quiz_test
  pool: 5
  timeout: 5000