development:
  adapter: postgresql
  host: localhost
  database: jaxon5_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: jaxon5_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: jaxon5
  pool: 5
  timeout: 5000