source 'https://rubygems.org'

gem 'rails', '3.2.14'


gem 'pg'
gem 'thin'


group :assets do
  gem 'sass-rails',   '~> 3.2.3'


  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

gem 'jquery-rails'

gem 'debugger'
